apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saurav-22/task-management-app-manifests.git
    path: charts/task-app
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: task-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
