# Helm values for Task App
image:
  tag: latest
replicaCount: 2
service:
  port: 80
  targetPort: 3000
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
autoscaling:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
rds:
  dbName: task_app
# dbHost, dbUser, dbPassword, are stored in Kubernetes Secret (secrets.yaml)
