# Kubernetes Secret for RDS credentials
apiVersion: v1
kind: Secret
metadata:
  name: rds-credentials
  namespace: task-app
type: Opaque
data:
  dbHost: dGFzay1hcHAuY3VjOWdxbXg4NnRwLmFwLXNvdXRoLTEucmRzLmFtYXpvbmF3cy5jb20=     # Replace with base64-encoded RDS endpoint
  dbUser: YWRtaW4=    # Replace with base64-encoded RDS username
  dbPassword: YWRtaW4xMjM0NQ== # Replace with base64-encoded RDS password

