---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: task-app
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: board-service
  namespace: task-app
  labels:
    app: board-service
spec:
  selector:
    app: board-service
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: task-app
  labels:
    app: task-service
spec:
  selector:
    app: task-service
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: task-app
  labels:
    app: comment-service
spec:
  selector:
    app: comment-service
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
